package images

import (
	"context"
	"errors"
	"fmt"
)

// Sentinel errors returned by Store and Process.
//
// HTTP status mapping (canonical; mirrored in internal/api/router.go and
// applied by internal/api/images.go):
//
//	ErrNotFound          → 404 IMAGE_NOT_FOUND
//	ErrTooLarge          → 413 CONTENT_TOO_LARGE
//	ErrUnsupportedFormat → 415 IMAGE_UNSUPPORTED
//	ErrAnimated          → 415 IMAGE_ANIMATED
//
// Any other error from Process or Store is treated as 500 INTERNAL_ERROR.
// Layers consuming this package match these sentinels via errors.Is.
var (
	ErrNotFound          = errors.New("images: not found")
	ErrTooLarge          = errors.New("images: payload exceeds size limit")
	ErrUnsupportedFormat = errors.New("images: unsupported image format")
	ErrAnimated          = errors.New("images: animated GIFs are not supported")
)

// IDLen is the canonical length, in hex characters, of an image content-hash
// ID generated by Put. Exported so the HTTP handler and MCP extractors can
// validate against one source of truth.
const IDLen = 16

// IDPatternFragment is the regex fragment matching a single canonical image
// ID. Callers anchor it (`^...$`) or splice it into a larger URL pattern.
// Built from IDLen so changing the ID shape (e.g. width, alphabet) is one
// edit, not several.
var IDPatternFragment = fmt.Sprintf(`[a-f0-9]{%d}`, IDLen)

// Store persists processed images keyed by content hash. Implementations must
// be safe for concurrent use.
type Store interface {
	// Put processes raw bytes, derives a content-hash ID, and persists the
	// result. Identical payloads are deduplicated - a second Put with the
	// same content returns the existing ID without inserting a new row.
	Put(ctx context.Context, raw []byte) (id string, contentType string, err error)

	// Get retrieves image bytes and content type by ID. Returns ErrNotFound
	// when no row matches.
	Get(ctx context.Context, id string) (data []byte, contentType string, err error)

	Close() error
}
